version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 